export const STATUS_MESSAGE: { [key: string]: string } = {
  NOT_FOUND: "Not Found",
  BAD_REQUEST: "Bad Request",
  SUCCESS: "Success",
  ERROR: "Error",
  NOT_AUTHORIZED: "Not Authorized",
  FORBIDDEN: "Forbidden",
  INTERNAL_SERVER_ERROR: "Internal Server Error",
  UNAUTHORIZED: "Unauthorized",
  CONFLICT: "Conflict",
  TOO_MANY_REQUEST: "Too Many Requests",
  NOT_IMPLEMENTED: "Not Implemented",
  SERVICE_UNAVAILABLE: "Service Unavailable",
  GATEWAY_TIMEOUT: "Gateway Timeout",
  PRECONDITION_FAILED: "Precondition Failed",
  NETWORK_AUTHENTICATION_REQUIRED: "Network Authentication Required",
  NETWORK_CONNECTION_ERROR: "Network Connection Error",
};
